import type { LocalizedLabel } from '@anavi/shared'

export interface SaimaShelf {
  slug: string
  // The cover's file. Named in English and apart from the slug: a slug is an address a visitor
  // reads, and a file name is a key nobody does.
  cover: string
  name: LocalizedLabel
  description: LocalizedLabel
}

// Shelf and product type share identical names: category section here corresponds directly to garment type.
export const SAIMA_SHELVES: SaimaShelf[] = [
  {
    slug: 'platya',
    cover: 'dresses',
    name: { ru: 'Платья', en: 'Dresses', ar: 'فساتين' },
    description: {
      ru: 'Миди, макси и сарафаны из крепа, льна и трикотажа — то, что шьётся тиражами и носится каждый день.',
      en: 'Midi, maxi dresses and sundresses in crepe, linen, and jersey — daily essentials crafted in volume.',
      ar: 'فساتين ميدي، ماكسي وسارافانات من الكريب والكتان والتريكو — قطع أساسية يومية تُنتج بكميات تجارية.',
    },
  },
  {
    slug: 'bluzy',
    cover: 'blouses',
    name: { ru: 'Блузы и рубашки', en: 'Blouses and shirts', ar: 'بلوزات وقمصان' },
    description: {
      ru: 'Поплин, лён и шёлк: от базового топа до блузы, в которой ходят на работу.',
      en: 'Poplin, linen, and silk: from basic tank tops to workday office blouses.',
      ar: 'بوبلين، كتان وحرير طبيعي: من التوب الأساسي اليومي إلى بلوزات العمل الأنيقة.',
    },
  },
  {
    slug: 'bryuki',
    cover: 'trousers',
    name: { ru: 'Брюки и юбки', en: 'Trousers and skirts', ar: 'بناطيل وتنانير' },
    description: {
      ru: 'Палаццо, прямые, джинсы и юбки — низ, который держит форму после стирки.',
      en: 'Palazzo, straight-leg trousers, jeans, and skirts designed to retain shape after washing.',
      ar: 'بناطيل بالاتزو، قصات مستقيمة، جينز وتنانير — قطع سفلية تحافظ على قوامها وجودتها بعد الغسيل.',
    },
  },
  {
    slug: 'trikotazh',
    cover: 'knitwear',
    name: { ru: 'Трикотаж', en: 'Knitwear', ar: 'تريكو وملابس محبوكة' },
    description: {
      ru: 'Футер, рибана и мериносовый микс: свитшоты, худи и джемперы своего вязания.',
      en: 'French terry, rib knit, and merino blends: in-house knitted sweatshirts, hoodies, and sweaters.',
      ar: 'أقمشة فوتر، ريبانا ومزيج صوف ميرينو: سويت شيرتات، هوديز وكنزات صوفية محبوكة في ورشتنا.',
    },
  },
  {
    slug: 'verhnyaya',
    cover: 'outerwear',
    name: { ru: 'Верхняя одежда', en: 'Outerwear', ar: 'ملابس خارجية ومعاطف' },
    description: {
      ru: 'Жакеты, тренчи и пальто — самая сложная часть цеха и самая долгая по срокам.',
      en: 'Tailored blazers, trench coats, and overcoats — our most intricate and detailed tailoring.',
      ar: 'بليزرات، ترنش كوت ومعاطف صوفية أنيقة — القسم الأكثر تعقيداً ودقة في ورشتنا.',
    },
  },
  {
    slug: 'komplekty',
    cover: 'sets',
    name: { ru: 'Костюмы и комплекты', en: 'Suits and matching sets', ar: 'أطقم وبدلات' },
    description: {
      ru: 'Двойки, которые продаются вместе: жакет с брюками, джемпер со штанами, рубашка с шортами.',
      en: 'Two-piece coordinated sets: blazer and trousers, sweater and pants, shirt and shorts.',
      ar: 'أطقم ثنائية متناسقة: بليزر مع بنطلون، كنزة صوف مع بنطلون، قميص مع شورت.',
    },
  },
]

/** The same silhouette in a different color forms a product line rather than a separate product: one card, multiple modifications. */
export interface SaimaColour {
  key: string
  suffix: LocalizedLabel
  cvet: string
}

export interface SaimaGarment {
  slug: string
  name: LocalizedLabel
  summary: LocalizedLabel
  text: LocalizedLabel
  price: number
  shelf: string
  cvet: string
  tkan: string
  sostav: string
  sezon: string[]
  sizes: number[]
  plotnost?: number
  dlina?: string
  rukav?: string
  posadka?: string
  podklad?: boolean
  predmetov?: number
  colours?: SaimaColour[]
}

const FULL = [42, 44, 46, 48, 50, 52, 54]
const SHORT = [42, 44, 46, 48, 50, 52]
const SMALL = [42, 44, 46, 48, 50]
const TALL = [44, 46, 48, 50, 52, 54]

export const SAIMA_GARMENTS: SaimaGarment[] = [
  {
    slug: 'plate-midi-poyas',
    name: { ru: 'Платье-миди с поясом', en: 'Belted midi dress', ar: 'فستان ميدي بحزام' },
    summary: {
      ru: 'Вискозный креп, мягкая сборка на талии, пояс из той же ткани',
      en: 'Viscose crepe, soft gathers at waist, self-fabric tie belt',
      ar: 'كريب فيسكوز ناعم، زمزمة خفيفة عند الخصر، حزام أنيق من نفس القماش',
    },
    text: {
      ru: 'Самая тиражная вещь цеха: креп садится по фигуре сборкой, а не вытачками, поэтому одно платье закрывает два соседних размера. Пояс из той же ткани, рукав-блузон на манжете с пуговицей.',
      en: 'Our most popular volume piece: fluid crepe drapes the silhouette with gentle gathering rather than darts, comfortably fitting adjacent sizes. Matching belt, blouson sleeve with button cuff.',
      ar: 'القطعة الأكثر إنتاجاً في ورشتنا: قماش الكريب ينسدل على القوام بزمزمات ناعمة بدون بنسات، ليغطي الفستان الواحد مقاسين متجاورين بسهولة. حزام من نفس القماش، وأكمام بلوزون أنيقة بأساور وأزرار.',
    },
    price: 3490,
    shelf: 'platya',
    cvet: 'pesochnyj',
    tkan: 'krep',
    sostav: 'viskoza-100',
    sezon: ['vesna', 'osen'],
    sizes: FULL,
    dlina: 'midi',
    colours: [
      {
        key: 'black',
        suffix: { ru: 'чёрное', en: 'black', ar: 'أسود' },
        cvet: 'chernyj',
      },
      {
        key: 'indigo',
        suffix: { ru: 'индиго', en: 'indigo', ar: 'نيلي' },
        cvet: 'indigo',
      },
    ],
  },
  {
    slug: 'plate-rubashka',
    name: { ru: 'Платье-рубашка', en: 'Shirt dress', ar: 'فستان قميص' },
    summary: {
      ru: 'Тенсел с матовым падением, полная планка на пуговицах, пояс в шлёвках',
      en: 'Matte-finish Tencel, full button placket, belt with loops',
      ar: 'تنسل بملمس مطفي انسيابي، صف أزرار كامل، حزام مع عرى تثبيت',
    },
    text: {
      ru: 'Тенсел ведёт себя как вискоза, но не мнётся в дороге — поэтому платье уезжает партиями в регионы. Классический воротник, накладной карман на груди, пояс снимается.',
      en: 'Tencel behaves like viscose but stays wrinkle-free in transit — a bestseller for regional retailers. Classic collar, patch chest pocket, detachable belt.',
      ar: 'قماش التنسل ينسدل كالفيسكوز ولا يتجعد أثناء النقل والشحن — لذلك يُطلب بكميات كبيرة للمتاجر. ياقة كلاسيكية، جيب صدر خارجي، وحزام قابل للإزالة.',
    },
    price: 3290,
    shelf: 'platya',
    cvet: 'indigo',
    tkan: 'tensel',
    sostav: 'tensel-100',
    sezon: ['vesna', 'leto'],
    sizes: FULL,
    dlina: 'midi',
  },
  {
    slug: 'plate-trikotazh',
    name: { ru: 'Платье трикотажное', en: 'Jersey dress', ar: 'فستان تريكو' },
    summary: {
      ru: 'Рибана в рубчик, высокий ворот, прямая колонна с разрезом сбоку',
      en: 'Rib knit fabric, fitted silhouette, side slit',
      ar: 'ريبانا مضلعة، ياقة عالية، قصة مستقيمة مع فتحة جانبية',
    },
    text: {
      ru: 'Рибана тянется в обе стороны, поэтому размерный ряд у платья короче обычного, а садится оно шире. Разрез сбоку — не украшение: без него шаг в прямой колонне короткий.',
      en: 'Dense ribbing holds shape and does not stretch out at the seat. Crew neck, long narrow sleeves, comfortable hem slit for walking.',
      ar: 'قماش الريبانا يتمدد في الاتجاهين مما يمنح مرونة واسعة في المقاسات وتغطية مريحة. الفتحة الجانبية أساسية لحرية الخطو والحركة في الفستان المستقيم.',
    },
    price: 2890,
    shelf: 'platya',
    cvet: 'grafit',
    tkan: 'ribana',
    sostav: 'hlopok-elastan',
    sezon: ['osen', 'zima'],
    sizes: FULL,
    dlina: 'midi',
  },
  {
    slug: 'plate-lnyanoe',
    name: { ru: 'Платье льняное', en: 'Linen dress', ar: 'فستان كتان' },
    summary: {
      ru: 'Стираный лён, широкие бретели, квадратный вырез и глубокие карманы',
      en: 'Washed softened linen, A-line silhouette, hidden side pockets',
      ar: 'كتان مغسول معالج، حمالات عريضة، ياقة مربعة وجيوب عميقة',
    },
    text: {
      ru: 'Лён стирается до мягкости ещё в цехе, поэтому вещь не садится после первой стирки дома. Заниженная линия талии и карманы в боковом шве.',
      en: "Pre-washed softened linen won't shrink after laundering. Relaxed silhouette, wide straps, side seam pockets.",
      ar: 'يُغسل الكتان حتى يكتسب أقصى درجات النعومة في الورشة قبل الخياطة، فلا يتقلص بعد الغسيل المنزلي. خصر منخفض وجيوب جانبية مخفية.',
    },
    price: 3190,
    shelf: 'platya',
    cvet: 'pesochnyj',
    tkan: 'len',
    sostav: 'len-100',
    sezon: ['leto'],
    sizes: FULL,
    dlina: 'midi',
  },
  {
    slug: 'plate-vechernee',
    name: { ru: 'Платье вечернее', en: 'Evening slip dress', ar: 'فستان سهرة' },
    summary: {
      ru: 'Креп-сатин, драпировка-хомут, косой крой и мягкие фалды в пол',
      en: 'Heavy silk with satin sheen, bias cut, delicate thin straps',
      ar: 'كريب ساتان، ياقة درابيه منسدلة، قصة مائلة وانسدال طويل حتى الأرض',
    },
    text: {
      ru: 'Косой крой — единственный в коллекции: раскрой идёт под сорок пять градусов, расход ткани в полтора раза выше обычного, и партия считается отдельно. Ряд короче — вещь садится точно по фигуре.',
      en: 'Bias-cut silk drapes softly along body contours. Clean neckline, adjustable thin straps, midi length.',
      ar: 'القصة المائلة الوحيدة في التشكيلة: يُقص القماش بزاوية 45 درجة باستهلاك قماش أعلى بمرة ونصف، وتُحسب دفعته بشكل خاص لضبط مقاسه الدقيق على الجسم.',
    },
    price: 5490,
    shelf: 'platya',
    cvet: 'bordo',
    tkan: 'satin',
    sostav: 'viskoza-100',
    sezon: ['bazovoe'],
    sizes: SMALL,
    dlina: 'maksi',
  },
  {
    slug: 'sarafan',
    name: { ru: 'Сарафан', en: 'Maxi sundress', ar: 'سارافان' },
    summary: {
      ru: 'Хлопковый твил, квадратный вырез, регулируемые бретели на пряжках',
      en: 'Cotton poplin, gathered tiered skirt, self-tie straps',
      ar: 'تويل قطني، ياقة مربعة، حمالات قابلة للتعديل بإبزيم',
    },
    text: {
      ru: 'Плотный твил держит форму сам, поэтому силуэт трапецией не оседает к вечеру. Бретели регулируются пряжками, накладные карманы отстрочены в два ряда.',
      en: 'Lightweight breathable poplin for hot summer days. Tiered volume, comfortable elasticized back bodice.',
      ar: 'قماش التويل المتين يحافظ على قوام القصة شبه المنحرفة طوال اليوم. حمالات قابلة لتعديل الطول، وجيوب خارجية بدرزات مزدوجة.',
    },
    price: 2690,
    shelf: 'platya',
    cvet: 'chernyj',
    tkan: 'tvil',
    sostav: 'hlopok-100',
    sezon: ['vesna', 'leto'],
    sizes: FULL,
    dlina: 'midi',
  },
  {
    slug: 'bluza-shelk',
    name: { ru: 'Блуза шёлковая', en: 'Silk blouse', ar: 'بلوزة حريرية' },
    summary: {
      ru: 'Шёлк песочной стирки, мягкий бант у горловины, спущенное плечо',
      en: 'Natural silk, concealed button placket, French cuffs',
      ar: 'حرير مغسول ناعم بملمس رملي مطفي، ربطة عنق ناعمة، أكتاف منسدلة',
    },
    text: {
      ru: 'Песочная стирка снимает с шёлка блеск, и блуза перестаёт быть нарядной — её носят с джинсами. Шьётся на тонкой игле, партия идёт медленнее остальных.',
      en: 'Classic tailored cut with concealed button front. Double cuffs with cufflinks or button closure.',
      ar: 'الغسيل الرملي يزيل اللمعان الزائد عن الحرير ليجعله مناسباً للإطلالات اليومية مع الجينز. تُخاط بإبر رفيعة وتستغرق وقتاً أطول في الإنتاج.',
    },
    price: 2890,
    shelf: 'bluzy',
    cvet: 'off-white',
    tkan: 'shelk',
    sostav: 'shelk-100',
    sezon: ['bazovoe'],
    sizes: FULL,
    rukav: 'dlinnyj',
    colours: [
      {
        key: 'black',
        suffix: { ru: 'чёрная', en: 'black', ar: 'أسود' },
        cvet: 'chernyj',
      },
    ],
  },
  {
    slug: 'rubashka-oversize',
    name: { ru: 'Рубашка оверсайз', en: 'Oversized shirt', ar: 'قميص فضفاض (أوفر سايز)' },
    summary: {
      ru: 'Хлопковый поплин, классический воротник, удлинённая спинка',
      en: 'Crisp cotton poplin, dropped shoulders, rounded hem',
      ar: 'بوبلين قطني، ياقة كلاسيكية، حاشية خلفية ممتدة',
    },
    text: {
      ru: 'Прямой корпус без вытачек и спущенное плечо: рубашка носится и навыпуск, и как лёгкий верх. Низ фигурный, спинка длиннее полочки на восемь сантиметров.',
      en: 'Relaxed loose boyfriend fit. Wear open over a tank top or tucked into high-rise trousers.',
      ar: 'قصة مستقيمة بدون بنسات وأكتاف منسدلة: يُرتدى مفتوحاً أو كطبقة خفيفة علوية. ظهر أطول من الأمام بثمانية سنتيمترات.',
    },
    price: 2190,
    shelf: 'bluzy',
    cvet: 'indigo',
    tkan: 'poplin',
    sostav: 'hlopok-100',
    sezon: ['vesna', 'leto'],
    sizes: FULL,
    rukav: 'dlinnyj',
    colours: [
      {
        key: 'white',
        suffix: { ru: 'белая', en: 'white', ar: 'أبيض' },
        cvet: 'belyj',
      },
    ],
  },
  {
    slug: 'bluza-volan',
    name: { ru: 'Блуза с воланом', en: 'Ruffled blouse', ar: 'بلوزة بكشكش' },
    summary: {
      ru: 'Вискоза, V-образный вырез с мягким воланом, запáх',
      en: 'Flowing viscose crepe, delicate ruffle along collar and placket',
      ar: 'فيسكوز انسيابي، ياقة V مع كشكش ناعم، قصة لف متقاطعة',
    },
    text: {
      ru: 'Волан выкроен по косой и потому лежит волной, а не складкой. Запáх фиксируется изнутри завязкой — вырез не расходится при движении.',
      en: 'Romantic blouse with soft ruffles framing the neckline and front placket. Keyhole back closure.',
      ar: 'الكشكش مقصوص بشكل مائل ليتدلى بتموجات انسيابية راقية. قصة اللف مثبتة برباط داخلي لمنع انفتاح الياقة أثناء الحركة.',
    },
    price: 1990,
    shelf: 'bluzy',
    cvet: 'pesochnyj',
    tkan: 'krep',
    sostav: 'viskoza-100',
    sezon: ['vesna', 'leto'],
    sizes: FULL,
    rukav: 'tri-chetverti',
  },
  {
    slug: 'rubashka-len',
    name: { ru: 'Рубашка льняная', en: 'Linen shirt', ar: 'قميص كتان' },
    summary: {
      ru: 'Стираный лён, отложной воротник, рукав на хлястике',
      en: 'Pure washed linen, straight relaxed fit, chest pocket',
      ar: 'كتان مغسول خفيف، ياقة قميص، أكمام قابلة للطي والتثبيت بشريط',
    },
    text: {
      ru: 'Лён в этой рубашке тоньше, чем в платье, — сто девяносто граммов, поэтому она носится и в жару. Рукав подворачивается и застёгивается на хлястик.',
      en: 'Breathable natural linen shirt. Retains casual elegance even with natural creasing.',
      ar: 'كتان بوزن 190 غرام خفيف ومثالي للأجواء الحارة. أكمام عملية يمكن طيها وتثبيتها بزر.',
    },
    price: 2490,
    shelf: 'bluzy',
    cvet: 'shalfej',
    tkan: 'len',
    sostav: 'len-100',
    sezon: ['leto'],
    sizes: FULL,
    rukav: 'dlinnyj',
  },
  {
    slug: 'top-bazovyj',
    name: { ru: 'Топ базовый', en: 'Essential tank top', ar: 'توب أساسي' },
    summary: {
      ru: 'Рибана, узкие бретели, обработанные края',
      en: 'Fine cotton jersey with elastane, wide straps, scoop neck',
      ar: 'ريبانا قطنية، حمالات رفيعة، حواف مشطبة بعناية',
    },
    text: {
      ru: 'Самая простая вещь коллекции и самая ходовая в опте: топ берут ростовками по пятьдесят штук и продают под своей маркой. Края обработаны бейкой из основной ткани.',
      en: 'Foundational wardrobe layer. Double-layered front for full opacity.',
      ar: 'القطعة الأبسط والأكثر رواجاً في المبيعات بالجملة: يُطلب بسلاسل المقاسات بالكامل لتسويقه تحت علامات تجارية مختلفة. الحواف مشطبة بشريط من نفس القماش.',
    },
    price: 890,
    shelf: 'bluzy',
    cvet: 'off-white',
    tkan: 'ribana',
    sostav: 'hlopok-elastan',
    sezon: ['bazovoe'],
    sizes: SHORT,
    rukav: 'bez-rukava',
  },
  {
    slug: 'bluza-poplin',
    name: { ru: 'Блуза поплиновая', en: 'Poplin wrap blouse', ar: 'بلوزة بوبلين' },
    summary: {
      ru: 'Плотный белый поплин, воротник-стойка, скрытая планка',
      en: 'Crisp cotton poplin, wrap front with side tie fastening',
      ar: 'بوبلين قطني أبيض متين، ياقة واقفة، صف أزرار مخفي',
    },
    text: {
      ru: 'Стойка держится за счёт дублирования, а не за счёт плотности ткани, поэтому воротник не ломается после стирки. Защипы на плече дают объём в рукаве без подкроя.',
      en: 'Flattering wrap construction accentuates the waistline. Elegant V-neckline and tailored long sleeves.',
      ar: 'الياقة الواقفة تحتفظ بصلابتها بفضل التدعيم الداخلي دون أن تتأثر بالغسيل. كسرات الأكتاف تمنح الأكمام اتساعاً مريحاً وأنيقاً.',
    },
    price: 2290,
    shelf: 'bluzy',
    cvet: 'belyj',
    tkan: 'poplin',
    sostav: 'hlopok-100',
    sezon: ['bazovoe'],
    sizes: FULL,
    rukav: 'dlinnyj',
  },
  {
    slug: 'bryuki-palacco',
    name: { ru: 'Брюки палаццо', en: 'Palazzo trousers', ar: 'بنطلون بالاتزو' },
    summary: {
      ru: 'Вискозный креп, высокая посадка, защипы и широкая штанина в пол',
      en: 'Flowing crepe fabric, high rise, wide straight leg',
      ar: 'كريب فيسكوز، خصر عالي، كسرات أمامية وأرجل واسعة ممتدة للأرض',
    },
    text: {
      ru: 'Креп даёт вес, из-за которого штанина падает вертикально и не парусит. Пояс широкий, застёжка сбоку — спереди ничего не ломает линию защипов.',
      en: 'Wide-leg silhouette with front pleats. Lengthens the silhouette; features side slant pockets and concealed zip.',
      ar: 'ثقل قماش الكريب يجعل الأرجل تسقط رأسياً بانسيابية تامة. خصر عالي مع سحاب جانبي يحافظ على استقامة الكسرات الأمامية.',
    },
    price: 2690,
    shelf: 'bryuki',
    cvet: 'grafit',
    tkan: 'krep',
    sostav: 'viskoza-100',
    sezon: ['vesna', 'osen'],
    sizes: FULL,
    plotnost: 150,
    posadka: 'vysokaya',
    colours: [
      {
        key: 'sand',
        suffix: { ru: 'песочные', en: 'sand', ar: 'رملي' },
        cvet: 'pesochnyj',
      },
    ],
  },
  {
    slug: 'bryuki-pryamye',
    name: { ru: 'Брюки прямые', en: 'Straight tailored trousers', ar: 'بنطلون كلاسيكي مستقيم' },
    summary: {
      ru: 'Шерстяной микс, высокая посадка, заутюженная стрелка',
      en: 'Suiting wool blend with elastane, pressed front creases',
      ar: 'مزيج صوف فاخر، خصر عالي، كسرة كية مكوية دائمة',
    },
    text: {
      ru: 'Стрелка закладывается прессом, а не утюгом, и держится до химчистки. Задние карманы в рамку, подклад до колена.',
      en: 'Classic office trousers with neat front creases. Comfortable waistband with belt loops.',
      ar: 'تُثبت الكسرة بالمكبس الحراري الصناعي لتدوم حتى التنظيف الجاف. جيوب خلفية مشقوقة وبطانة داخلية حتى الركبة.',
    },
    price: 2890,
    shelf: 'bryuki',
    cvet: 'grafit',
    tkan: 'sherst',
    sostav: 'sherst-pe',
    sezon: ['osen', 'zima'],
    sizes: FULL,
    plotnost: 240,
    posadka: 'vysokaya',
  },
  {
    slug: 'dzhinsy-mom',
    name: { ru: 'Джинсы mom', en: 'Mom fit jeans', ar: 'بنطلون جينز مام فيت' },
    summary: {
      ru: 'Плотный деним без стрейча, зауженная штанина, укороченная длина',
      en: 'Heavyweight 100% cotton denim, high rise, tapered leg',
      ar: 'جينز قطني سميك غير مطاطي، أرجل مدببة وطول قصير للكاحل',
    },
    text: {
      ru: 'Деним без эластана — вещь садится по фигуре не сразу, а после второй носки, и это нормально для такой посадки. Клёпки медные, застёжка на пуговицах.',
      en: 'Authentic non-stretch raw denim that softens beautifully with wear. Classic 5-pocket styling.',
      ar: 'دينيم طبيعي بدون إيلاستين يأخذ شكل الجسم تدريجياً مع الاستخدام. مسامير نحاسية متينة وأزرار أصلية.',
    },
    price: 2990,
    shelf: 'bryuki',
    cvet: 'indigo',
    tkan: 'denim',
    sostav: 'hlopok-100',
    sezon: ['bazovoe'],
    sizes: SHORT,
    plotnost: 340,
    posadka: 'vysokaya',
    colours: [
      {
        key: 'black',
        suffix: { ru: 'чёрные', en: 'black', ar: 'أسود' },
        cvet: 'chernyj',
      },
    ],
  },
  {
    slug: 'yubka-midi',
    name: { ru: 'Юбка-миди', en: 'Midi A-line skirt', ar: 'تنورة ميدي' },
    summary: {
      ru: 'Креп-сатин по косой, гладкий пояс, мягкий расклёш от бедра',
      en: 'Washed linen blend, front button fastening, side pockets',
      ar: 'كريب ساتان مقصوص بزاوية مائلة، حزام خصر ناعم، اتساع ناعم من الورك',
    },
    text: {
      ru: 'Косой крой даёт расклёш без единой складки на поясе. Молния втачана в боковой шов потайной строчкой.',
      en: 'Flared midi skirt with tonal buttons down the center front. Fitted waistband with elasticated back insert.',
      ar: 'القصة المائلة تمنح التنورة اتساعاً انسيابياً جميلاً بدون أي طيات أو كسرات عند الخصر. سحاب جانبي مخفي بخياطة دقيقة.',
    },
    price: 2190,
    shelf: 'bryuki',
    cvet: 'pesochnyj',
    tkan: 'satin',
    sostav: 'viskoza-100',
    sezon: ['vesna', 'leto'],
    sizes: FULL,
    plotnost: 140,
    posadka: 'srednyaya',
  },
  {
    slug: 'yubka-karandash',
    name: { ru: 'Юбка-карандаш', en: 'Pencil skirt', ar: 'تنورة قلم رصاص (بنسل)' },
    summary: {
      ru: 'Шерстяной микс, высокий пояс, рельефы и шлица',
      en: 'Dense jersey with stretch, high waist, back vent',
      ar: 'مزيج صوف فاخر، حزام خصر عالي، قصات برنسيس وشق خلفي',
    },
    text: {
      ru: 'Силуэт держат рельефы, а не вытачки, — юбка садится ровнее на широком бедре. Шлица сзади подшита вручную.',
      en: 'Tailored silhouette with comfortable stretch for ease of movement. Back slit and invisible zipper.',
      ar: 'القصات الطولية تضبط القوام وتمنح ثباتاً ممتازاً عند الورك. الشق الخلفي مشطب يدوياً بحرفية تامة.',
    },
    price: 2090,
    shelf: 'bryuki',
    cvet: 'chernyj',
    tkan: 'sherst',
    sostav: 'sherst-pe',
    sezon: ['osen', 'zima'],
    sizes: FULL,
    plotnost: 240,
    posadka: 'vysokaya',
  },
  {
    slug: 'shorty',
    name: { ru: 'Шорты', en: 'Tailored linen shorts', ar: 'شورت' },
    summary: {
      ru: 'Лён, высокая посадка, защипы и отвороты',
      en: 'Pure linen, mid-thigh length, front pleats and side pockets',
      ar: 'كتان نقي، خصر عالي، كسرات أمامية وأطراف مطوية',
    },
    text: {
      ru: 'Отвороты закреплены изнутри, чтобы не разворачивались после стирки. Карманы боковые, глубокие — в них помещается телефон.',
      en: 'City shorts with refined tailoring. Pairs perfectly with matching linen blazers or casual tees.',
      ar: 'الأطراف المطوية مثبتة بدرزات مخفية لمنع تفككها بعد الغسيل. جيوب جانبية عميقة تتسع للهاتف بسهولة.',
    },
    price: 1690,
    shelf: 'bryuki',
    cvet: 'pesochnyj',
    tkan: 'len',
    sostav: 'len-100',
    sezon: ['leto'],
    sizes: FULL,
    plotnost: 190,
    posadka: 'vysokaya',
  },
  {
    slug: 'svitshot',
    name: { ru: 'Свитшот', en: 'Crewneck sweatshirt', ar: 'سويت شيرت' },
    summary: {
      ru: 'Футер с начёсом, спущенное плечо, реглан, резинка по низу',
      en: 'Fleece-backed French terry, ribbed collar, cuffs and hem',
      ar: 'فوتر دافئ مبطن، أكتاف منسدلة، أكمام راجلان وأطراف مطاطية',
    },
    text: {
      ru: 'Триста двадцать граммов — тот вес, на котором футер ещё не тяжёлый, но уже не просвечивает. Резинка своя, в цвет полотна, а не покупная лента.',
      en: 'Heavyweight cotton fleece interior for warmth. Relaxed unisex fit with reinforced flatlock stitching.',
      ar: 'قماش فوتر بوزن 320 غرام يمنح الدفء دون أن يكون ثقيلاً. أطراف مضلعة محاكة من نفس خيوط القماش بدقة.',
    },
    price: 1890,
    shelf: 'trikotazh',
    cvet: 'seryj-melanzh',
    tkan: 'futer',
    sostav: 'hlopok-100',
    sezon: ['osen', 'vesna'],
    sizes: TALL,
    plotnost: 320,
    colours: [
      {
        key: 'sand',
        suffix: { ru: 'песочный', en: 'sand', ar: 'رملي' },
        cvet: 'pesochnyj',
      },
      {
        key: 'indigo',
        suffix: { ru: 'индиго', en: 'indigo', ar: 'نيلي' },
        cvet: 'indigo',
      },
    ],
  },
  {
    slug: 'hudi',
    name: { ru: 'Худи', en: 'Oversized hoodie', ar: 'هودي' },
    summary: {
      ru: 'Плотный футер, двухслойный капюшон, карман-кенгуру',
      en: 'Dense French terry, double-layered hood, kangaroo pocket',
      ar: 'فوتر سميك فاخر، قبعة مزدوجة الطبقات، جيب كنغر أمامي',
    },
    text: {
      ru: 'Четыреста граммов и капюшон в два слоя: вещь зимняя, под куртку. Люверсы металлические, шнур плоский.',
      en: 'Comfortable spacious hood without drawstrings, dropped shoulders, roomy front pouch pocket.',
      ar: 'قماش ثقيل بوزن 400 غرام وقبعة بطبقتين مناسبة لفصل الشتاء تحت المعاطف. فتحات معدنية متينة ورباط عريض.',
    },
    price: 2290,
    shelf: 'trikotazh',
    cvet: 'indigo',
    tkan: 'futer',
    sostav: 'hlopok-100',
    sezon: ['osen', 'zima'],
    sizes: TALL,
    plotnost: 400,
  },
  {
    slug: 'longsliv',
    name: { ru: 'Лонгслив', en: 'Long sleeve tee', ar: 'بلوزة بأكمام طويلة (لونغ سليف)' },
    summary: {
      ru: 'Тонкая рибана, высокий ворот, узкие манжеты',
      en: 'Soft combed cotton jersey, classic crew neck, regular fit',
      ar: 'ريبانا قطنية ناعمة، ياقة عالية، أساور ضيقة',
    },
    text: {
      ru: 'Рибана сто восемьдесят граммов — лонгслив носится под низ и не добавляет объёма. Ворот двойной, не растягивается через голову.',
      en: 'Everyday layering essential in pure breathable cotton with ribbed neckline.',
      ar: 'ريبانا خفيفة بوزن 180 غرام مثالية للارتداء كطبقة داخلية دون إضافة حجم. ياقة مزدوجة لا تتمدد مع الارتداء.',
    },
    price: 1190,
    shelf: 'trikotazh',
    cvet: 'grafit',
    tkan: 'ribana',
    sostav: 'hlopok-elastan',
    sezon: ['bazovoe'],
    sizes: SHORT,
    plotnost: 180,
  },
  {
    slug: 'futbolka',
    name: { ru: 'Футболка', en: 'Classic cotton T-shirt', ar: 'تي شيرت' },
    summary: {
      ru: 'Плотная кулирка, укреплённое плечо, двойная строчка по низу',
      en: 'Medium-weight 100% cotton, relaxed boxy cut, ribbed crew neck',
      ar: 'قطن ناعم عالي الكثافة، أكتاف معززة، درزة مزدوجة سفلية',
    },
    text: {
      ru: 'Плечевой шов проложен тесьмой — футболка не перекручивается после десятой стирки. Вторая по объёму позиция в опте после базового топа.',
      en: 'Universal crewneck t-shirt with clean finish. Holds shape wash after wash.',
      ar: 'درزة الكتف مدعمة بشريط داخلي يمنع التواء التي شيرت بعد الغسيل المتكرر. ثاني أعلى المنتجات مبيعاً في الجملة بعد التوب.',
    },
    price: 890,
    shelf: 'trikotazh',
    cvet: 'off-white',
    tkan: 'dzhersi',
    sostav: 'hlopok-100',
    sezon: ['bazovoe'],
    sizes: SHORT,
    plotnost: 190,
    colours: [
      {
        key: 'black',
        suffix: { ru: 'чёрная', en: 'black', ar: 'أسود' },
        cvet: 'chernyj',
      },
    ],
  },
  {
    slug: 'kardigan',
    name: { ru: 'Кардиган', en: 'V-neck knit cardigan', ar: 'كارديجان' },
    summary: {
      ru: 'Мериносовый микс, V-вырез, пять пуговиц, спущенное плечо',
      en: 'Merino wool blend, button-front closure, ribbed trims',
      ar: 'مزيج صوف ميرينو، ياقة V، خمسة أزرار، أكتاف منسدلة',
    },
    text: {
      ru: 'Вяжется на стороне, шьётся у нас: полотно приходит купонами, раскрой идёт по контуру. Резинка по борту и низу связана заодно с деталью.',
      en: 'Knit on fine-gauge machines with soft thermal warmth. Natural horn-effect buttons.',
      ar: 'تُحاك الألواح وتُفصل في ورشتنا بدقة. الحواف المضلعة محبوكة مباشرة مع القطعة لضمان تماسكها.',
    },
    price: 2990,
    shelf: 'trikotazh',
    cvet: 'pesochnyj',
    tkan: 'merinos',
    sostav: 'sherst-akril',
    sezon: ['osen', 'zima'],
    sizes: SHORT,
    plotnost: 280,
  },
  {
    slug: 'dzhemper',
    name: { ru: 'Джемпер', en: 'Crewneck sweater', ar: 'كنزة صوفية' },
    summary: {
      ru: 'Шерстяной микс, круглый вырез, крупная резинка по низу и манжетам',
      en: 'Soft wool-acrylic blend, relaxed silhouette, dropped shoulders',
      ar: 'مزيج صوف دافئ، ياقة دائرية، أطراف وأساور مضلعة عريضة',
    },
    text: {
      ru: 'Оверсайз посажен на размер больше нормы, поэтому ряд короче: сорок восьмой закрывает и пятидесятый. Резинка крупная, три на три.',
      en: 'Cozy knit pullover with ribbed collar and hem. Non-itchy lightweight warmth.',
      ar: 'قصة أوفر سايز واسعة ومريحة بحياكة مضلعة عريضة (3×3) توفر الدفء والأناقة.',
    },
    price: 2690,
    shelf: 'trikotazh',
    cvet: 'ovsyanyj',
    tkan: 'sherst',
    sostav: 'sherst-akril',
    sezon: ['osen', 'zima'],
    sizes: SHORT,
    plotnost: 340,
  },
  {
    slug: 'zhaket',
    name: { ru: 'Жакет', en: 'Single-breasted blazer', ar: 'بليزر' },
    summary: {
      ru: 'Шерстяной микс, английский воротник, два накладных кармана',
      en: 'Tailored wool blend, notch lapels, flap pockets, full lining',
      ar: 'مزيج صوف فاخر، ياقة كلاسيكية مشقوقة، جيبان خارجيان',
    },
    text: {
      ru: 'Полуподклад: спинка на подкладе до талии, полочка целиком — жакет носится и в межсезонье. Плечо мягкое, без подплечника.',
      en: 'Structured tailoring with light shoulder pads. Flap front pockets and single button fastening.',
      ar: 'نصف بطانة: ظهر مبطن حتى الخصر وأمام مبطن بالكامل ليلائم جميع فصول السنة. أكتاف مريحة بدون حشوات سميكة.',
    },
    price: 4290,
    shelf: 'verhnyaya',
    cvet: 'grafit',
    tkan: 'sherst',
    sostav: 'sherst-pe',
    sezon: ['vesna', 'osen'],
    sizes: TALL,
    podklad: true,
    colours: [
      {
        key: 'sand',
        suffix: { ru: 'песочный', en: 'sand', ar: 'رملي' },
        cvet: 'pesochnyj',
      },
    ],
  },
  {
    slug: 'trench',
    name: { ru: 'Тренч', en: 'Classic trench coat', ar: 'ترنش كوت' },
    summary: {
      ru: 'Хлопковый габардин, двубортная застёжка, пояс на пряжке',
      en: 'Water-repellent cotton twill, double-breasted, belt with buckle',
      ar: 'غاباردين قطني، صفين أزرار، حزام بإبزيم معدني',
    },
    text: {
      ru: 'Самая долгая вещь в цехе: тридцать восемь операций и две примерки на образце. Ветрозащитная планка, шлица сзади, пояс на металлической пряжке.',
      en: 'Authentic double-breasted trench with storm flap, epaulettes, and buckled belt.',
      ar: 'القطعة الأكثر دقة في الورشة: 38 مرحلة خياطة وبروفات متعددة على العينة. غطاء حماية من الرياح وشق خلفي وحزام بإبزيم معدني.',
    },
    price: 5990,
    shelf: 'verhnyaya',
    cvet: 'pesochnyj',
    tkan: 'gabardin',
    sostav: 'hlopok-100',
    sezon: ['vesna', 'osen'],
    sizes: TALL,
    podklad: true,
    colours: [
      {
        key: 'black',
        suffix: { ru: 'чёрный', en: 'black', ar: 'أسود' },
        cvet: 'chernyj',
      },
    ],
  },
  {
    slug: 'palto',
    name: { ru: 'Пальто', en: 'Wool wrap coat', ar: 'معطف صوف' },
    summary: {
      ru: 'Шерстяной микс, скрытая застёжка, глубокие прорезные карманы',
      en: '70% wool blend, unlined tailored finish, tie belt and patch pockets',
      ar: 'مزيج صوف فاخر، صف أزرار مخفي، جيوب شق عميقة',
    },
    text: {
      ru: 'Прямой силуэт без вытачек — пальто носится и на объёмный джемпер. Застёжка скрытая: снаружи ни одной пуговицы.',
      en: 'Minimalist wrap silhouette with wide lapels and deep patch pockets. Fits over bulky knits.',
      ar: 'قصة مستقيمة بدون بنسات تتسع لارتدائه فوق الكنزات الصوفية السميكة. أزرار مخفية بالكامل لمنح مظهر أمامي أنيق وناعم.',
    },
    price: 6490,
    shelf: 'verhnyaya',
    cvet: 'grafit',
    tkan: 'sherst',
    sostav: 'sherst-pe',
    sezon: ['osen', 'zima'],
    sizes: TALL,
    podklad: true,
  },
  {
    slug: 'zhilet-udlinennyj',
    name: { ru: 'Жилет удлинённый', en: 'Longline tailored vest', ar: 'سديري (جيليه) طويل' },
    summary: {
      ru: 'Шерстяной микс, V-вырез, две пуговицы, разрезы по бокам',
      en: 'Structured suiting fabric, sleeveless, peak lapels, welt pockets',
      ar: 'مزيج صوف بدلات، ياقة V، زران أماميان، فتحات جانبية',
    },
    text: {
      ru: 'Без подклада и без рукава — самая быстрая вещь верхней полки, четырнадцать операций. Носится поверх рубашки как третий слой.',
      en: 'Sophisticated longline vest for effortless layering over shirts or knitwear.',
      ar: 'بدون بطانة وبدون أكمام — أسرع قطعة في قسم الملابس الخارجية (14 مرحلة خياطة). يُرتدى فوق القمصان كطبقة ثالثة راقية.',
    },
    price: 2890,
    shelf: 'verhnyaya',
    cvet: 'grafit',
    tkan: 'sherst',
    sostav: 'sherst-pe',
    sezon: ['vesna', 'osen'],
    sizes: TALL,
    podklad: false,
  },
  {
    slug: 'bomber',
    name: { ru: 'Бомбер', en: 'Insulated bomber jacket', ar: 'جاكيت بومبر' },
    summary: {
      ru: 'Стираный хлопковый твил, резинка на воротнике и манжетах, молния',
      en: 'Smooth matte nylon, light thermal insulation, ribbed trims',
      ar: 'تويل قطني مغسول، ياقة وأساور مضلعة، سحاب كامل',
    },
    text: {
      ru: 'Твил стирается энзимами до мягкости, поэтому бомбер не стоит колом на первой носке. Молния разъёмная, два прорезных кармана.',
      en: 'Modern bomber with ribbed collar and cuffs. Metal front zip and slanted snap pockets.',
      ar: 'تويل مغسول بالإنزيمات لمنح مرونة وملمس ناعم من أول ارتداء. سحاب معدني متين وجيبان مشقوقان.',
    },
    price: 3490,
    shelf: 'verhnyaya',
    cvet: 'indigo',
    tkan: 'tvil',
    sostav: 'hlopok-100',
    sezon: ['vesna', 'osen'],
    sizes: TALL,
    podklad: true,
  },
  {
    slug: 'plash-lnyanoj',
    name: { ru: 'Плащ льняной', en: 'Linen duster coat', ar: 'معطف كتان صيفي (دستر كوت)' },
    summary: {
      ru: 'Стираный лён без подклада, скрытая застёжка, накладные карманы',
      en: 'Heavy softened linen, loose relaxed cut, deep patch pockets',
      ar: 'كتان مغسول ثقيل بدون بطانة، صف أزرار مخفي، جيوب خارجية',
    },
    text: {
      ru: 'Летняя верхняя вещь: лён двести сорок граммов, ни подклада, ни дублирования, кроме воротника. Швы обработаны запошивочным — изнанка чистая.',
      en: 'Unlined lightweight summer coat. Perfect cover-up for warm breezy evenings.',
      ar: 'معطف صيفي خفيف من الكتان عالي الجودة بوزن 240 غرام بدون بطانة. درزات داخلية مغلقة ونظيفة تماماً.',
    },
    price: 3890,
    shelf: 'verhnyaya',
    cvet: 'pesochnyj',
    tkan: 'len',
    sostav: 'len-100',
    sezon: ['leto'],
    sizes: TALL,
    podklad: false,
  },
  {
    slug: 'kostyum-bryuki',
    name: { ru: 'Костюм с брюками', en: 'Two-piece trouser suit', ar: 'بدلة مع بنطلون' },
    summary: {
      ru: 'Шерстяной микс: жакет с английским воротником и прямые брюки со стрелкой',
      en: 'Single-breasted blazer and wide-leg trousers in matching suiting fabric',
      ar: 'مزيج صوف فاخر: بليزر بياقة كلاسيكية وبنطلون مستقيم مع كسرة',
    },
    text: {
      ru: 'Продаётся комплектом и шьётся комплектом: жакет и брюки кроятся из одного рулона, чтобы оттенок совпал. Размер один на обе вещи.',
      en: 'Coordinated tailored power suit. Blazer and trousers can also be styled separately.',
      ar: 'تُفصل وتُخاط معاً من نفس رول القماش لضمان تطابق الألوان بنسبة 100%. مقاس موحد للقطعتين.',
    },
    price: 6990,
    shelf: 'komplekty',
    cvet: 'grafit',
    tkan: 'sherst',
    sostav: 'sherst-pe',
    sezon: ['osen', 'zima'],
    sizes: SMALL,
    predmetov: 2,
  },
  {
    slug: 'kostyum-yubka',
    name: { ru: 'Костюм с юбкой', en: 'Skirt suit', ar: 'بدلة مع تنورة' },
    summary: {
      ru: 'Шерстяной микс: приталенный жакет и юбка-карандаш с высоким поясом',
      en: 'Cropped tailored jacket and A-line mini skirt in textured tweed',
      ar: 'مزيج صوف فاخر: جاكيت محدد للقوام وتنورة قلم رصاص بخصر عالي',
    },
    text: {
      ru: 'Тот же принцип одного рулона, что и у брючного. Жакет приталенный, на полном подкладе, юбка со шлицей.',
      en: 'Contemporary two-piece set featuring a boxy cropped jacket and matching high-waisted skirt.',
      ar: 'مفصلة من نفس رول القماش. جاكيت ببطانة كاملة وتنورة رسمية مع شق خلفي للحركة.',
    },
    price: 6290,
    shelf: 'komplekty',
    cvet: 'chernyj',
    tkan: 'sherst',
    sostav: 'sherst-pe',
    sezon: ['osen', 'zima'],
    sizes: SMALL,
    predmetov: 2,
  },
  {
    slug: 'kostyum-trikotazh',
    name: { ru: 'Костюм трикотажный', en: 'Knitwear lounge set', ar: 'طقم تريكو كاجوال' },
    summary: {
      ru: 'Мериносовый микс: джемпер с круглым вырезом и широкие брюки на резинке',
      en: 'Fine-gauge ribbed sweater and wide-leg knit pants',
      ar: 'مزيج صوف ميرينو: كنزة دائرية الياقة وبنطلون واسع بخصر مطاطي',
    },
    text: {
      ru: 'Домашний по ощущению и выходной по виду — из-за этого берут парами. Пояс брюк на широкой резинке, без кулиски.',
      en: 'Ultra-soft loungewear set in merino blend. Elasticized knit waistband.',
      ar: 'مريح كالملابس المنزلية وأنيق كملابس الخروج — يُطلب بكثرة. خصر البنطلون مزود بمطاط عريض ومريح.',
    },
    price: 4490,
    shelf: 'komplekty',
    cvet: 'ovsyanyj',
    tkan: 'merinos',
    sostav: 'sherst-akril',
    sezon: ['osen', 'zima'],
    sizes: SHORT,
    predmetov: 2,
  },
  {
    slug: 'kostyum-len',
    name: { ru: 'Костюм льняной', en: 'Linen two-piece set', ar: 'طقم كتان صيفي' },
    summary: {
      ru: 'Стираный лён: рубашка с отложным воротником и шорты с отворотами',
      en: 'Short-sleeve linen shirt and drawstring shorts',
      ar: 'كتان مغسول: قميص بياقة مطوية وشورت بأطراف مقلوبة',
    },
    text: {
      ru: 'Летний комплект, который чаще всего уезжает в Казахстан: лёгкий, дышит, не требует глажки после дороги.',
      en: 'Resort-ready matching set in breathable pure washed linen.',
      ar: 'طقم صيفي خفيف ومنعش وقابل للتنفس لا يتطلب كياً مستمراً ومثالي للسفر والإجازات.',
    },
    price: 3990,
    shelf: 'komplekty',
    cvet: 'pesochnyj',
    tkan: 'len',
    sostav: 'len-100',
    sezon: ['leto'],
    sizes: SHORT,
    predmetov: 2,
  },
  {
    slug: 'kostyum-sportivnyj',
    name: { ru: 'Костюм спортивный', en: 'Fleece tracksuit', ar: 'بدلة رياضية دافئة' },
    summary: {
      ru: 'Футер: худи на молнии и джоггеры с манжетами',
      en: 'Zip-up hoodie and tapered sweatpants in fleece-backed French terry',
      ar: 'فوتر دافئ: هودي بسحاب وبنطلون جوغر بأساور',
    },
    text: {
      ru: 'Худи на молнии, а не через голову: комплект надевают поверх, а не вместо. Джоггеры на резинке с кулиской, манжеты по низу.',
      en: 'Premium cozy loungewear tracksuit with ribbed trims and deep pockets.',
      ar: 'هودي بسحاب كامل لسهولة ارتدائه كطبقة علوية، وبنطلون بأساور مريحة وحبل شد للخصر.',
    },
    price: 3290,
    shelf: 'komplekty',
    cvet: 'seryj-melanzh',
    tkan: 'futer',
    sostav: 'hlopok-100',
    sezon: ['osen', 'vesna'],
    sizes: SHORT,
    predmetov: 2,
  },
  {
    slug: 'komplekt-domashnij',
    name: { ru: 'Комплект домашний', en: 'Home lounge set', ar: 'طقم منزلي مريح' },
    summary: {
      ru: 'Мягкий хлопковый джерси: лонгслив и широкие брюки на кулиске',
      en: 'Soft cotton jersey camisole top and relaxed shorts',
      ar: 'جيرسي قطني ناعم: بلوزة بأكمام طويلة وبنطلون واسع برباط سحب',
    },
    text: {
      ru: 'Самый дешёвый комплект и самый простой в отшиве — двенадцать операций на обе вещи. Кулиска продета шнуром в цвет.',
      en: 'Breathable comfortable sleep and home set with delicate elastic trim.',
      ar: 'طقم منزلي خفيف وسهل الإنتاج (12 مرحلة خياطة). خصر مريح برباط سحب متناسق مع لون القماش.',
    },
    price: 2490,
    shelf: 'komplekty',
    cvet: 'grafit',
    tkan: 'dzhersi',
    sostav: 'hlopok-100',
    sezon: ['bazovoe'],
    sizes: SHORT,
    predmetov: 2,
  },
]
